import type { Metadata } from "next";
import "./globals.css";
import "antd/dist/reset.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Course dan",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <NuqsAdapter>
          <Providers>
            <main>{children}</main>
          </Providers>
        </NuqsAdapter>
      </body>
    </html>
  );
}
